<?php

$query_array=array("headline"=>__("List All Printers"),
                   "sql"=>"SELECT other_id, other_linked_pc, other_network_name, other_description, other_p_port_name, other_location, other_type, other_ip_address FROM other WHERE other_type = 'printer' ",
                   "sort"=>"other_network_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to Printer"),
                                "var"=>array("other"=>"%other_id",
                                             "view"=>"printer",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"other_linked_pc",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"other_network_name",
                                               "head"=>__("Attached Device"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"system.php",
                                                            "title"=>__("Go to System"),
                                                            "var"=>array("pc"=>"%other_linked_pc",
                                                                         "view"=>"summary",
                                                                        ),
                                                           ),
                                              ),
                                   "30"=>array("name"=>"other_description",
                                               "head"=>__("Description"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                              
                                   "40"=>array("name"=>"other_p_port_name",
                                               "head"=>__("Port"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"other_type",
                                               "head"=>__("Type"),
                                               "show"=>"n",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
